[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310"]

[tool.ruff]
line-length = 120
ignore = ["E741"]

[tool.ruff.per-file-ignores]
"test.py" = ["E501"]

[dependency-groups]
dev = [
    "wtpsplit>=2.1.7",
    "onnx",
    "onnxscript",
    "onnxruntime>=1.23.2",
]
